# Generated by Django 4.2.7 on 2023-11-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuqoroMurojat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=500, verbose_name='Fuqaroning familyasi, ismi va sharifi')),
                ('passportid', models.CharField(max_length=500, verbose_name='Fuqaroning pasport seriyasi va raqami')),
                ('jshshir', models.CharField(max_length=500, verbose_name='JSHSHIR')),
                ('tshnomi', models.CharField(max_length=500, verbose_name='Tuman/shahar nomi')),
                ('yashmanzil', models.CharField(max_length=500, verbose_name="Yashash manzili (pasportdagi ma'lumot)")),
                ('kraqami', models.CharField(max_length=500, verbose_name='Turar joy kadastr raqami')),
                ('ksoni', models.IntegerField(verbose_name="Olingan ko'mir miqdori (tonnada)")),
                ('rasm', models.CharField(max_length=500, verbose_name="Ma'lumot uchun rasm")),
                ('tel', models.IntegerField(verbose_name='Telefon raqami')),
                ('qachonOlgan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TashkilotMurojat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnomi', models.CharField(max_length=500, verbose_name='Tashkilot nomi')),
                ('tkim', models.CharField(max_length=500, verbose_name='Tashkilotda kim bo`lib ishlashingiz')),
                ('qachonOlgan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
